version: '3'

services:
  # https://hub.docker.com/_/nginx
  web-nginx:
    image: nginx
    volumes: 
      - ./:/usr/share/nginx/html:ro
    ports: 
      - "8081:80"
    expose:
      - 80
    networks:
      - grid         

  # https://github.com/SeleniumHQ/docker-selenium
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    networks:
      - grid      

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - grid      

  firefox:
    image: selenium/node-firefox:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub
    networks:
      - grid      

  test-chrome:
    build: robot-image
    command: -v BROWSER:chrome --outputdir /out /robot-tests
    volumes:
      # Share robot tests with container
      - ./robot-image/robot-tests:/robot-tests:ro
      - ./results/chrome:/out:rw
    depends_on:
      - web-nginx
      - chrome
    networks:
      - grid

  test-firefox:
    build: robot-image
    command: -v BROWSER:firefox --outputdir /out /robot-tests
    volumes:
      # Share robot tests with container
      - ./robot-image/robot-tests:/robot-tests:ro
      - ./results/firefox:/out:rw
    depends_on:
      - web-nginx
      - firefox
    networks:
      - grid      

networks:
  grid:
