version: '3'

services:
  # https://hub.docker.com/_/nginx
  web-nginx:
    image: nginx
    volumes: 
      - ./:/usr/share/nginx/html:ro
    ports: 
      - "8081:80"
    expose:
      - 80    

  # https://github.com/SeleniumHQ/docker-selenium
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  firefox:
    image: selenium/node-firefox:3.141.59-neon
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub 

  test-chrome:
    build: robot-image
    command: -v BROWSER:chrome --outputdir /results /robot-tests
    volumes:
      # Share robot tests and results with container
      - ./robot-image/robot-tests:/robot-tests:ro
      - ./results/chrome:/results:rw
    depends_on:
      - web-nginx
      - chrome

  test-firefox:
    build: robot-image
    command: -v BROWSER:firefox --outputdir /results /robot-tests
    volumes:
      # Share robot tests and results with container
      - ./robot-image/robot-tests:/robot-tests:ro
      - ./results/firefox:/results:rw
    depends_on:
      - web-nginx
      - firefox
